// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxpteboxxlhnihimsocb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cHRlYm94eGxobmloaW1zb2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzAyNzAsImV4cCI6MjA2Njk0NjI3MH0.NBt_x95vL7VljlC2TT63VFLMhZ829kO48nTxINdequU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});